# Generated by Django 5.2.5 on 2025-09-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='An IP address that is explicitly blocked.', unique=True, verbose_name='Blocked IP Address')),
                ('reason', models.CharField(blank=True, help_text="Reason for blocking this IP, e.g., 'spam bot', 'brute force attack'.", max_length=255, null=True, verbose_name='Reason for Block')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this IP was added to the blacklist.', verbose_name='Blocked At')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
