# Generated by Django 5.2.5 on 2025-09-03 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedip',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Blocked IP', 'verbose_name_plural': 'Blocked IPs'},
        ),
        migrations.RemoveField(
            model_name='blockedip',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blockedip',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The time the IP was blocked.', verbose_name='Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='The IP address that has been blocked.', unique=True, verbose_name='Blocked IP Address'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='reason',
            field=models.TextField(blank=True, default=django.utils.timezone.now, help_text='The reason why this IP address was blocked.', verbose_name='Reason for Block'),
            preserve_default=False,
        ),
    ]
